apiVersion: v2
name: jellyfin-wrapper
type: application
version: 0.1.0
appVersion: "2.7.0"

dependencies:
  - name: jellyfin
    version: "2.7.0"
    repository: https://jellyfin.github.io/jellyfin-helm
