apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raspberry-flavoured
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PMW9905/app-of-apps.git
    path: charts/raspberry-flavoured
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
