gitea:
  persistence:
    enabled: true
    storageClass: gitea-storageclass

  # Disable default ingress
  ingress:
    enabled: false

  service:
    http:
      type: ClusterIP
      port: 3000

  gitea:
    config:
      server:
        PROTOCOL: http  
        DOMAIN: gitea.parkiki.org
        ROOT_URL: https://gitea.parkiki.org
        SSH_DOMAIN: gitea.parkiki.org
        HTTP_PORT: 3000

  postgresql-ha:
    enabled: false

  postgresql:
    enabled: true
    persistence:
      enabled: true
      storageClass: gitea-postgresql-storageclass
      size: 10Gi
