apiVersion: v2
name: tailscale-operator-wrapper
type: application
version: 0.1.0
appVersion: "1.92.4"

dependencies:
  - name: tailscale-operator
    version: "1.92.4"
    repository: https://pkgs.tailscale.com/helmcharts
