apiVersion: v1
kind: Service
metadata:
  name: raspberry-flavoured
  namespace: minecraft
spec:
  selector:
    app: raspberry-flavoured
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
  type: ClusterIP
