apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raspberry-flavoured-data
  namespace: minecraft
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: raspberry-flavoured-storageclass
  resources:
    requests:
      storage: 20Gi
