---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jellyfin-media-storageclass
provisioner: nfs.csi.k8s.io
parameters:
  server: truenas.parkiki.org
  share: /mnt/HDDPool/k3s
  subDir: jellyfin-media
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jellyfin-config-storageclass
provisioner: nfs.csi.k8s.io
parameters:
  server: truenas.parkiki.org
  share: /mnt/HDDPool/k3s
  subDir: jellyfin-config
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jellyfin-cache-storageclass
provisioner: nfs.csi.k8s.io
parameters:
  server: truenas.parkiki.org
  share: /mnt/HDDPool/k3s
  subDir: jellyfin-cache
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
