apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
spec:
  defaultBackend:
    service:
      name: gitea-application-http
      port:
        number: 3000
  ingressClassName: tailscale
  tls:
    - hosts:
        - gitea
