apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-application-http
  namespace: gitea
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitea.parkiki.org`)
      kind: Rule
      services:
        - name: gitea-application-http
          port: 3000
  tls:
    certResolver: letsencrypt
