apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-ingressroute
  namespace: gitea
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitea.parkiki.org`)
      kind: Rule
      services:
        - name: gitea-http
          port: 3000
  tls:
    certResolver: letsencrypt
