apiVersion: v1
kind: Service
metadata:
  name: nextcloud-external
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 30027
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nextcloud-external
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.127.155
    ports:
      - port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nextcloud.parkiki.org`)
      kind: Rule
      services:
        - name: nextcloud-external
          port: 80
  tls:
    certResolver: letsencrypt
