apiVersion: v1
kind: Service
metadata:
  name: nextcloud-external
  namespace: default
spec:
  type: ExternalName
  externalName: 192.168.127.155
  ports:
    - port: 30027
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nextcloud.parkiki.org`)
      kind: Rule
      services:
        - name: nextcloud-external
          port: 30027
  tls:
    certResolver: letsencrypt
